export async function getServerSideProps({ res }) {
  const base = process.env.NEXT_PUBLIC_URL || 'https://prisvardatestet.vercel.app';
  const pages = [{"path":"","priority":"1.0","changefreq":"daily"},{"path":"/om-oss","priority":"0.5","changefreq":"monthly"},{"path":"/kontakt","priority":"0.4","changefreq":"monthly"},{"path":"/integritetspolicy","priority":"0.3","changefreq":"yearly"},{"path":"/horlur","priority":"0.8","changefreq":"weekly"},{"path":"/laptop","priority":"0.8","changefreq":"weekly"},{"path":"/mobiltelefon","priority":"0.8","changefreq":"weekly"},{"path":"/surfplatta","priority":"0.8","changefreq":"weekly"},{"path":"/smartwatch","priority":"0.8","changefreq":"weekly"},{"path":"/jamfor/sony-wf-sp900-vs-jabra-elite-active-75t","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/sony-wf-sp900-vs-bose-sport-earbuds","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/sony-wf-sp900-vs-anker-soundcore-spirit-x2","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/sony-wf-sp900-vs-jaybird-vista-2","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/sony-wf-sp900-vs-plantronics-backbeat-fit-3150","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/sony-wf-sp900-vs-beats-powerbeats-pro","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/jabra-elite-active-75t-vs-bose-sport-earbuds","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/jabra-elite-active-75t-vs-anker-soundcore-spirit-x2","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/jabra-elite-active-75t-vs-jaybird-vista-2","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/jabra-elite-active-75t-vs-plantronics-backbeat-fit-3150","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/jabra-elite-active-75t-vs-beats-powerbeats-pro","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/bose-sport-earbuds-vs-anker-soundcore-spirit-x2","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/bose-sport-earbuds-vs-jaybird-vista-2","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/bose-sport-earbuds-vs-plantronics-backbeat-fit-3150","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/bose-sport-earbuds-vs-beats-powerbeats-pro","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/anker-soundcore-spirit-x2-vs-jaybird-vista-2","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/anker-soundcore-spirit-x2-vs-plantronics-backbeat-fit-3150","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/anker-soundcore-spirit-x2-vs-beats-powerbeats-pro","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/jaybird-vista-2-vs-plantronics-backbeat-fit-3150","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/jaybird-vista-2-vs-beats-powerbeats-pro","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/plantronics-backbeat-fit-3150-vs-beats-powerbeats-pro","priority":"0.7","changefreq":"weekly"}];
  const xml = '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' +
    pages.map(function(p) { return '<url><loc>'+base+p.path+'</loc><lastmod>2026-06-24</lastmod><changefreq>'+p.changefreq+'</changefreq><priority>'+p.priority+'</priority></url>'; }).join('') +
    '</urlset>';
  res.setHeader('Content-Type', 'application/xml');
  res.setHeader('Cache-Control', 's-maxage=86400, stale-while-revalidate');
  res.write(xml); res.end();
  return { props: {} };
}
export default function Sitemap() { return null; }